<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>fbognini.Infrastructure</PackageId>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <Description>Persistence, multitenancy and repository implementations for fbognini projects.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Snickler.EFCore" Version="3.0.0" />
    <PackageReference Include="FastIDs.TypeId.Serialization.SystemTextJson" Version="1.1.1" />
    <PackageReference Include="FastIDs.TypeId.Serialization.JsonNet" Version="1.1.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(ExtensionsVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(ExtensionsVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(ExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="$(ExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" Version="6.13.1" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" Version="6.13.1" />
    <PackageReference Include="EFCore.BulkExtensions" Version="8.1.3" />
    <PackageReference Include="linq2db.EntityFrameworkCore" Version="8.1.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fbognini.Core.Domain\fbognini.Core.Domain.csproj" />
  </ItemGroup>

</Project>
