<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>fbognini.Core</PackageId>
    <Description>A class library with core implementations for fbognini projects.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LinqKit.Core" Version="1.2.11" />
  </ItemGroup>

</Project>
