<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>fbognini.Core.Domain</PackageId>
    <Description>Domain primitives for fbognini projects.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fbognini.Core\fbognini.Core.csproj" />
  </ItemGroup>

</Project>
